version: "3.4"

services:
  minecraft:
    container_name: minecraft
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MINECRAFT_VERSION: ${MINECRAFT_VERSION}
    restart: unless-stopped
    volumes:
      - ./config/banned-ips.json:/minecraft/banned-ips.json
      - ./config/banned-players.json:/minecraft/banned-players.json
      - ./config/ops.json:/minecraft/ops.json
      - ./config/whitelist.json:/minecraft/whitelist.json
      - ./config/server.properties:/minecraft/server.properties
      - ./config/geyser-config.yml:/minecraft/plugins/Geyser-Spigot/config.yml
      - world:/minecraft/world
    ports:
      - "${JAVA_PORT}:25565/tcp" # Java port
      - "${BEDROCK_PORT}:19132/udp" # Bedrock port
    environment:
      - JAVA_OPTIONS=${JAVA_OPTIONS}

volumes:
  world:
