version: "3.4"

services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MINECRAFT_VERSION: ${MINECRAFT_VERSION}
    restart: unless-stopped
    volumes:
      - ./config/banned-ips.json:/minecraft/banned-ips.json
      - ./config/banned-players.json:/minecraft/banned-players.json
      - ./config/ops.json:/minecraft/ops.json
      - ./config/whitelist.json:/minecraft/whitelist.json
      - ./config/server.properties:/minecraft/server.properties
      - ./config/geyser-config.yml:/minecraft/plugins/Geyser-Spigot/config.yml
      - ./worlds/world:/minecraft/world
      - ./worlds/world_the_end:/minecraft/world_the_end
      - ./worlds/world_nether:/minecraft/world_nether
    ports:
      - "${JAVA_PORT}:25565/tcp"
      - "${BEDROCK_PORT}:19132/udp"
    environment:
      - JAVA_OPTIONS=${JAVA_OPTIONS}
