version: "3.4"

services:
  spigot-geysermc-floodgate:
    container_name: spigot-geysermc-floodgate
    image: spigot-geysermc-floodgate
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./server.properties:/minecraft/server.properties
      - ./geyser-config.yml:/minecraft/plugins/Geyser-Spigot/config.yml
      - ./world:/minecraft/world
      - ./world_nether:/minecraft/world_nether
      - ./world_the_end:/minecraft/world_the_end
    ports:
      - "25565:25565" # Java port
      - "19132:19132" # Bedrock port
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

